"""各区の主要5町データ（不動産価格・需要情報）"""

TOWNS_DATA = {
    "chiyoda": [
        {"name": "番町", "name_en": "Banchō",
         "mansion": "350〜550万円/㎡", "land": "600万円〜/㎡",
         "feature": "都内最高格の住宅地。大使館・要人が居住するステータスエリアで供給が極めて少なく、出れば必ず複数の引き合いが来る。",
         "feature_en": "Tokyo's most prestigious residential address. Home to embassies and VIPs; supply is extremely limited — every listing attracts multiple competing inquiries.",
         "feature_zh": "东京最高格住宅地，大使馆及要人聚居，供给极度稀缺，每次上市必有多方竞相问询。",
         "demand": "政財界VIP・外資高官・企業オーナー",
         "demand_en": "Political & financial VIPs, foreign exec housing, corporate owners",
         "demand_zh": "政财界VIP・外资高官・企业主",
         "trend": "強い上昇"},
        {"name": "麹町", "name_en": "Kōjimachi",
         "mansion": "280〜450万円/㎡", "land": "500〜700万円/㎡",
         "feature": "永田町・霞が関に隣接。法人社宅・政治家・官僚の居住需要が厚く、高値成約事例が多い。",
         "feature_en": "Adjacent to Nagatachō and Kasumigaseki. Deep corporate housing demand from politicians and bureaucrats; above-market closings are common.",
         "feature_zh": "毗邻永田町、霞关，法人社宅、政治家及官僚居住需求旺盛，高价成交案例多见。",
         "demand": "政治家・大企業役員・外資社宅",
         "demand_en": "Politicians, senior executives, foreign corporate housing",
         "demand_zh": "政治家・大企业役员・外资社宅",
         "trend": "上昇"},
        {"name": "丸の内", "name_en": "Marunouchi",
         "mansion": "300〜500万円/㎡", "land": "800万円〜/㎡",
         "feature": "都内最高格のビジネス街。居住用物件は極めて希少で、外資ファンドが直接取得するケースが多い。",
         "feature_en": "Tokyo's premier business district. Residential listings are extremely rare; foreign real estate funds acquire directly.",
         "feature_zh": "东京最高格商务区，住宅物件极度稀缺，外资基金直接收购案例多见。",
         "demand": "外資ファンド・大企業社宅",
         "demand_en": "Foreign real estate funds, corporate housing",
         "demand_zh": "外资基金・大企业社宅",
         "trend": "強い上昇"},
        {"name": "神田", "name_en": "Kanda",
         "mansion": "150〜260万円/㎡", "land": "250〜400万円/㎡",
         "feature": "再開発が進む商業エリア。収益物件・IT系企業需要が旺盛で、投資家の注目度が高い。",
         "feature_en": "Redeveloping commercial zone. Strong demand from income property investors and IT firms; high investor attention.",
         "feature_zh": "再开发持续推进的商业区，收益物件及IT企业需求旺盛，投资者关注度高。",
         "demand": "収益物件投資家・IT系法人",
         "demand_en": "Income property investors, IT sector firms",
         "demand_zh": "收益物件投资者・IT系法人",
         "trend": "再開発期待で上昇"},
        {"name": "秋葉原", "name_en": "Akihabara",
         "mansion": "150〜250万円/㎡", "land": "250〜380万円/㎡",
         "feature": "インバウンド需要と商業開発で変貌中。民泊・ホテル転用需要が強く、多様な出口が取れる。",
         "feature_en": "Transforming through inbound tourism and commercial development. Strong minpaku and hotel conversion demand; diverse exit options.",
         "feature_zh": "因入境旅游及商业开发而蜕变中，民宿及酒店转用需求强劲，出口选择多元。",
         "demand": "IT系投資家・インバウンド事業者",
         "demand_en": "IT sector investors, inbound operators",
         "demand_zh": "IT系投资者・入境事业者",
         "trend": "上昇"},
    ],
    "chuo": [
        {"name": "月島", "name_en": "Tsukishima",
         "mansion": "150〜250万円/㎡", "land": "200〜300万円/㎡",
         "feature": "下町情緒と湾岸利便性を兼備。もんじゃ文化のブランドが観光需要を生み、投資物件としての付加価値がある。",
         "feature_en": "Combines shitamachi atmosphere with waterfront convenience. Monjayaki culture generates tourism demand, adding investment value.",
         "feature_zh": "兼具下町风情与湾岸便利性，文字烧文化带来旅游需求，投资物件附加价值显著。",
         "demand": "ファミリー実需・投資家",
         "demand_en": "Families, investors",
         "demand_zh": "家庭实需・投资者",
         "trend": "上昇"},
        {"name": "勝どき", "name_en": "Kachidoki",
         "mansion": "140〜240万円/㎡", "land": "200〜290万円/㎡",
         "feature": "タワーマンション集積エリア。都心直結の利便性と湾岸ビューで、成約価格が継続上昇中。",
         "feature_en": "Tower apartment concentration zone. Direct city access and bay views drive consistent price increases.",
         "feature_zh": "塔楼公寓集中区，都心直连便利性及湾岸景观带动成交价格持续上涨。",
         "demand": "DINKs・ファミリー・投資家",
         "demand_en": "DINKs, families, investors",
         "demand_zh": "丁克族・家庭・投资者",
         "trend": "上昇"},
        {"name": "晴海", "name_en": "Harumi",
         "mansion": "130〜220万円/㎡", "land": "200〜280万円/㎡",
         "feature": "五輪選手村跡地の大規模開発エリア。インフラ整備が完了し、都心アクセスが大幅向上。",
         "feature_en": "Large-scale development on the former Olympic athletes' village site. Infrastructure complete; city access dramatically improved.",
         "feature_zh": "奥运选手村遗址大规模开发区，基础设施完善，都心可达性大幅提升。",
         "demand": "ファミリー・都心移住者",
         "demand_en": "Families, urban migrants",
         "demand_zh": "家庭・都心移居者",
         "trend": "上昇"},
        {"name": "銀座", "name_en": "Ginza",
         "mansion": "280〜450万円/㎡", "land": "500万円〜/㎡",
         "feature": "国内外のブランド最高地。居住物件は極めて希少で、外国人富裕層・法人需要が常に旺盛。",
         "feature_en": "Japan's most prestigious commercial address. Residential listings extremely rare; consistent strong demand from wealthy foreign buyers and corporations.",
         "feature_zh": "日本最高格商业地址，住宅物件极度稀缺，外国富裕层及法人需求始终旺盛。",
         "demand": "外国人富裕層・外資法人",
         "demand_en": "Affluent foreign buyers, foreign corporations",
         "demand_zh": "外国富裕层・外资法人",
         "trend": "強い上昇"},
        {"name": "日本橋", "name_en": "Nihonbashi",
         "mansion": "200〜350万円/㎡", "land": "350〜550万円/㎡",
         "feature": "金融機関・外資系金融の社宅需要が強い。老舗文化の高いブランド力が価格を支える。",
         "feature_en": "Strong corporate housing demand from financial institutions and foreign finance firms. The traditional brand supports prices.",
         "feature_zh": "金融机关及外资金融机构社宅需求强劲，老字号文化的高品牌力支撑价格。",
         "demand": "金融系法人・富裕層",
         "demand_en": "Financial sector corporations, affluent buyers",
         "demand_zh": "金融系法人・富裕层",
         "trend": "安定上昇"},
    ],
    "minato": [
        {"name": "麻布台", "name_en": "Azabūdai",
         "mansion": "400〜600万円/㎡", "land": "600万円〜/㎡",
         "feature": "麻布台ヒルズ開業でブランド力が急上昇。外資ファンドが積極取得中で、相場を超えた成約事例が増加。",
         "feature_en": "Brand value surged after Azabūdai Hills opened. Foreign funds actively acquiring; above-market closings multiplying.",
         "feature_zh": "麻布台山丘开业后品牌力急速上升，外资基金积极收购，超市场价成交案例持续增加。",
         "demand": "外資ファンド・超富裕層",
         "demand_en": "Foreign real estate funds, ultra-affluent buyers",
         "demand_zh": "外资基金・超富裕层",
         "trend": "急上昇"},
        {"name": "白金台", "name_en": "Shirokanedai",
         "mansion": "300〜500万円/㎡", "land": "500〜800万円/㎡",
         "feature": "都内屈指の高級住宅地。国内富裕層・外国人の邸宅需要が根強く、土地・戸建ての希少性が高い。",
         "feature_en": "One of Tokyo's premier residential areas. Deep demand from domestic affluent buyers and foreign VIPs for land and detached homes.",
         "feature_zh": "东京屈指可数的高级住宅地，国内富裕层及外籍人士邸宅需求根深蒂固，土地及独栋住宅稀缺性高。",
         "demand": "国内富裕層・外国人VIP",
         "demand_en": "Affluent domestic buyers, foreign VIPs",
         "demand_zh": "国内富裕层・外国VIP",
         "trend": "強い上昇"},
        {"name": "三田", "name_en": "Mita",
         "mansion": "250〜400万円/㎡", "land": "400〜600万円/㎡",
         "feature": "慶應大学隣接で文教価値も高い。外資系企業本社周辺の社宅需要が厚く、法人取引が多い。",
         "feature_en": "High educational value from adjacent Keio University. Strong corporate housing demand from foreign company HQs; frequent institutional transactions.",
         "feature_zh": "毗邻庆应大学，文教价值高，外资企业总部周边社宅需求旺盛，法人交易频繁。",
         "demand": "外資法人・教育重視層",
         "demand_en": "Foreign corporations, education-focused buyers",
         "demand_zh": "外资法人・重视教育层",
         "trend": "上昇"},
        {"name": "芝浦", "name_en": "Shibaura",
         "mansion": "200〜350万円/㎡", "land": "300〜500万円/㎡",
         "feature": "再開発が続く湾岸エリア。タワーマンションの新築・中古ともに需要が旺盛で流動性が高い。",
         "feature_en": "Ongoing waterfront redevelopment. Both new and resale tower apartment demand is strong; high liquidity.",
         "feature_zh": "湾岸再开发持续进行，塔楼新築及中古需求均旺盛，市场流动性高。",
         "demand": "DINKs・投資家・外国人",
         "demand_en": "DINKs, investors, foreign residents",
         "demand_zh": "丁克族・投资者・外籍人士",
         "trend": "上昇"},
        {"name": "南麻布", "name_en": "Minami-Azabu",
         "mansion": "280〜450万円/㎡", "land": "400〜650万円/㎡",
         "feature": "大使館街に隣接し外国人居住者が多い。外貨建て購入の買い手も多く、相場以上の成約が期待できる。",
         "feature_en": "Embassy district adjacency brings many foreign residents. Foreign currency buyers are common; above-market closings are achievable.",
         "feature_zh": "毗邻大使馆街，外国居民众多，外币购买买方多，可期待高于市场行情的成交。",
         "demand": "外国人富裕層・大使館関係者",
         "demand_en": "Affluent foreign buyers, embassy-related residents",
         "demand_zh": "外国富裕层・大使馆相关人士",
         "trend": "上昇"},
    ],
    "shinjuku": [
        {"name": "四谷", "name_en": "Yotsuya",
         "mansion": "200〜340万円/㎡", "land": "300〜480万円/㎡",
         "feature": "皇居外苑に近い高格住宅地。閑静な環境と都心利便性を兼備し、富裕層・外国人の居住需要が高い。",
         "feature_en": "Premium residential area close to the Imperial Palace grounds. Quiet environment and city convenience; high demand from affluent and foreign buyers.",
         "feature_zh": "毗邻皇居外苑的高格住宅地，兼具宁静环境与都心便利性，富裕层及外籍人士居住需求旺盛。",
         "demand": "富裕層・外国人・法人社宅",
         "demand_en": "Affluent buyers, foreign residents, corporate housing",
         "demand_zh": "富裕层・外籍人士・法人社宅",
         "trend": "安定上昇"},
        {"name": "市ヶ谷", "name_en": "Ichigaya",
         "mansion": "200〜340万円/㎡", "land": "300〜470万円/㎡",
         "feature": "防衛省・法律事務所が集積するエリア。法曹・公務員需要が厚く、安定した成約が続く。",
         "feature_en": "Cluster of Ministry of Defense and law firms. Thick legal professional and civil servant demand; consistent stable closings.",
         "feature_zh": "防卫省及律师事务所云集，法律专业人士及公务员需求旺盛，成交稳定持续。",
         "demand": "法曹・公務員・外資社宅",
         "demand_en": "Legal professionals, civil servants, foreign corporate housing",
         "demand_zh": "法律专业人士・公务员・外资社宅",
         "trend": "安定上昇"},
        {"name": "神楽坂", "name_en": "Kagurazaka",
         "mansion": "180〜300万円/㎡", "land": "280〜440万円/㎡",
         "feature": "フランス人街としても有名な高感度エリア。外国人居住者の定着率が高く、外貨購入者が多い。",
         "feature_en": "Known as the French quarter; high-profile lifestyle area. High long-term foreign resident retention; many foreign currency purchasers.",
         "feature_zh": "以法国人街闻名的高品位区域，外国居民定居率高，外币购买者众多。",
         "demand": "外国人富裕層・クリエイター",
         "demand_en": "Affluent foreign buyers, creatives",
         "demand_zh": "外国富裕层・创意人士",
         "trend": "上昇"},
        {"name": "西新宿", "name_en": "Nishi-Shinjuku",
         "mansion": "160〜270万円/㎡", "land": "250〜400万円/㎡",
         "feature": "大企業本社街に近い高層住宅エリア。エグゼクティブ需要・法人社宅として高値成約が多い。",
         "feature_en": "High-rise residential area near major corporate HQs. Frequent above-market executive and corporate housing closings.",
         "feature_zh": "毗邻大企业总部的高层住宅区，高管及法人社宅高价成交案例多见。",
         "demand": "大企業役員・外資社宅",
         "demand_en": "Senior corporate executives, foreign corporate housing",
         "demand_zh": "大企业役员・外资社宅",
         "trend": "上昇"},
        {"name": "落合", "name_en": "Ochiai",
         "mansion": "130〜220万円/㎡", "land": "200〜320万円/㎡",
         "feature": "芸術家・クリエイターが多く住む閑静な住宅地。独自のカルチャー価値が不動産評価に乗る。",
         "feature_en": "Quiet residential area with many artists and creatives. Unique cultural value layers onto real estate pricing.",
         "feature_zh": "艺术家及创意人士众多的宁静住宅地，独特的文化价值叠加于不动产估价之上。",
         "demand": "クリエイター・ファミリー実需",
         "demand_en": "Creatives, family real demand",
         "demand_zh": "创意人士・家庭实需",
         "trend": "緩やかな上昇"},
    ],
    "bunkyo": [
        {"name": "本郷", "name_en": "Hongō",
         "mansion": "200〜320万円/㎡", "land": "300〜450万円/㎡",
         "feature": "東大に隣接する文教の中枢。研究者・医師・教授職の居住需要が根強く、知識層向け物件として特別な価値がある。",
         "feature_en": "Academic heart adjacent to UTokyo. Deep residential demand from researchers, doctors, and professors; properties hold special value for the educated class.",
         "feature_zh": "毗邻东京大学的文教核心，研究者、医师及教授职居住需求根深蒂固，作为知识层物件具有特殊价值。",
         "demand": "研究者・医師・大学教授",
         "demand_en": "Researchers, physicians, university professors",
         "demand_zh": "研究者・医师・大学教授",
         "trend": "安定上昇"},
        {"name": "小石川", "name_en": "Koishikawa",
         "mansion": "180〜280万円/㎡", "land": "260〜400万円/㎡",
         "feature": "歴史ある高級住宅地と公園緑地が共存。閑静な環境と都心利便性を評価する富裕層の需要が安定。",
         "feature_en": "Historic premium residential area alongside park greenery. Stable affluent demand for quiet environment and city convenience.",
         "feature_zh": "历史悠久的高级住宅地与公园绿地共存，重视宁静环境与都心便利性的富裕层需求稳定。",
         "demand": "富裕層・ファミリー",
         "demand_en": "Affluent buyers, families",
         "demand_zh": "富裕层・家庭",
         "trend": "安定"},
        {"name": "千駄木", "name_en": "Sendagi",
         "mansion": "160〜260万円/㎡", "land": "240〜360万円/㎡",
         "feature": "谷中・根津とともに「谷根千」エリアの一角。下町ブランドの再評価で若年富裕層・外国人の移住が増加。",
         "feature_en": "Part of the 'Yanesen' area with Yanaka and Nezu. Re-evaluation of the shitamachi brand is attracting younger affluent buyers and foreign residents.",
         "feature_zh": "与谷中、根津共同构成'谷根千'区域，下町品牌再评价带动年轻富裕层及外籍人士移居增加。",
         "demand": "若年富裕層・外国人クリエイター",
         "demand_en": "Young affluent buyers, foreign creatives",
         "demand_zh": "年轻富裕层・外国创意人士",
         "trend": "上昇"},
        {"name": "白山", "name_en": "Hakusan",
         "mansion": "150〜250万円/㎡", "land": "220〜350万円/㎡",
         "feature": "白山神社を中心とした落ち着いた住宅地。文京区内で比較的手頃な価格帯で、ファミリー実需が安定。",
         "feature_en": "Calm residential area centered on Hakusan Shrine. Relatively affordable within Bunkyo; stable family real demand.",
         "feature_zh": "以白山神社为中心的宁静住宅地，在文京区内价格相对合理，家庭实需稳定。",
         "demand": "子育て世代・ファミリー",
         "demand_en": "Child-rearing generation, families",
         "demand_zh": "育儿世代・家庭",
         "trend": "緩やかな上昇"},
        {"name": "本駒込", "name_en": "Honkomagome",
         "mansion": "160〜270万円/㎡", "land": "240〜380万円/㎡",
         "feature": "六義園・東洋文庫など文化施設に囲まれた住宅地。静かな環境を好む高齢富裕層の需要が根強い。",
         "feature_en": "Residential area surrounded by cultural facilities like Rikugien and Toyo Bunko. Deep demand from wealthy older buyers who prize quiet surroundings.",
         "feature_zh": "周围环绕六义园、东洋文库等文化设施，偏爱宁静环境的高龄富裕层需求根深蒂固。",
         "demand": "富裕高齢層・ファミリー",
         "demand_en": "Wealthy older buyers, families",
         "demand_zh": "富裕高龄层・家庭",
         "trend": "安定"},
    ],
    "taito": [
        {"name": "浅草", "name_en": "Asakusa",
         "mansion": "120〜200万円/㎡", "land": "180〜280万円/㎡",
         "feature": "インバウンド需要のメッカ。外国人投資家が収益物件を積極取得中。「浅草」の住所が海外でもブランド価値を持つ。",
         "feature_en": "Mecca for inbound demand. Foreign investors actively acquiring income properties. The 'Asakusa' address carries brand value even overseas.",
         "feature_zh": "入境需求的圣地，外国投资者积极收购收益物件，'浅草'地址在海外亦具有品牌价值。",
         "demand": "外国人投資家・民泊事業者",
         "demand_en": "Foreign investors, minpaku operators",
         "demand_zh": "外国投资者・民宿运营者",
         "trend": "急上昇"},
        {"name": "蔵前", "name_en": "Kuramae",
         "mansion": "130〜210万円/㎡", "land": "190〜290万円/㎡",
         "feature": "クラフト・アートの聖地として急成長。クリエイター移住が加速しており、エリアブランドが形成されつつある。",
         "feature_en": "Rapidly growing as a craft and art destination. Creator migration is accelerating; area brand is forming fast.",
         "feature_zh": "作为工艺与艺术圣地急速成长，创意人士移居加速，区域品牌正在快速形成。",
         "demand": "クリエイター・若年富裕層",
         "demand_en": "Creatives, young affluent buyers",
         "demand_zh": "创意人士・年轻富裕层",
         "trend": "急上昇"},
        {"name": "上野", "name_en": "Ueno",
         "mansion": "130〜210万円/㎡", "land": "200〜300万円/㎡",
         "feature": "国立博物館・芸術大学を擁する文化エリア。インバウンド商業需要と教育需要が共存し、物件価値が上昇中。",
         "feature_en": "Cultural area with national museums and arts universities. Inbound commercial demand and educational demand coexist; property values rising.",
         "feature_zh": "拥有国立博物馆及艺术大学的文化区，入境商业需求与教育需求并存，物件价值持续上升。",
         "demand": "外国人投資家・教育関係者",
         "demand_en": "Foreign investors, education-related buyers",
         "demand_zh": "外国投资者・教育相关人士",
         "trend": "上昇"},
        {"name": "谷中", "name_en": "Yanaka",
         "mansion": "100〜180万円/㎡", "land": "160〜260万円/㎡",
         "feature": "「谷根千」ブランドの中心地。古い建物・長屋のリノベ需要が非常に高く、通常評価より高く売れる可能性がある。",
         "feature_en": "Center of the Yanesen brand. Very high renovation demand for old buildings and nagaya row houses; potential to sell above standard appraisal.",
         "feature_zh": "'谷根千'品牌的中心地，旧建筑及长屋改建需求极高，有望以超出标准评估的价格出售。",
         "demand": "リノベ投資家・外国人クリエイター",
         "demand_en": "Renovation investors, foreign creatives",
         "demand_zh": "改建投资者・外国创意人士",
         "trend": "上昇"},
        {"name": "根岸", "name_en": "Negishi",
         "mansion": "100〜170万円/㎡", "land": "150〜240万円/㎡",
         "feature": "下町の静かな住宅地。台東区内でも価格が手頃で、投資家の利回り需要が安定している。",
         "feature_en": "Quiet shitamachi residential area. Relatively affordable even within Taito; stable yield-seeking investor demand.",
         "feature_zh": "下町宁静住宅地，在台东区内价格相对合理，投资者利回需求稳定。",
         "demand": "投資家・地元実需",
         "demand_en": "Investors, local real demand",
         "demand_zh": "投资者・本地实需",
         "trend": "緩やかな上昇"},
    ],
    "sumida": [
        {"name": "押上", "name_en": "Oshiage",
         "mansion": "100〜180万円/㎡", "land": "160〜250万円/㎡",
         "feature": "スカイツリーの麓で観光需要が旺盛。外国人観光客向けの収益物件として外資ネットワーク経由の引き合いが多い。",
         "feature_en": "Strong tourism demand at the base of Sky Tree. Many foreign-network inquiries for income properties targeting inbound tourists.",
         "feature_zh": "晴空塔脚下观光需求旺盛，面向外国游客的收益物件通过外资网络询盘众多。",
         "demand": "インバウンド投資家・収益物件目的",
         "demand_en": "Inbound investors, income property seekers",
         "demand_zh": "入境投资者・收益物件目的",
         "trend": "上昇"},
        {"name": "錦糸町", "name_en": "Kinshichō",
         "mansion": "110〜180万円/㎡", "land": "170〜260万円/㎡",
         "feature": "再開発と商業施設充実で急成長。都心へのアクセスが良く、ビジネスパーソンの賃貸需要が厚い。",
         "feature_en": "Fast-growing through redevelopment and commercial expansion. Good city access; thick rental demand from business workers.",
         "feature_zh": "因再开发及商业设施完善而快速成长，都心可达性优良，商务人士租赁需求旺盛。",
         "demand": "投資家・単身ビジネス層",
         "demand_en": "Investors, single business professionals",
         "demand_zh": "投资者・单身商务层",
         "trend": "上昇"},
        {"name": "両国", "name_en": "Ryōgoku",
         "mansion": "100〜170万円/㎡", "land": "160〜250万円/㎡",
         "feature": "国技館・江戸東京博物館を擁する文化エリア。外国人観光客の定期来訪でエリア認知度が上昇中。",
         "feature_en": "Cultural area with Kokugikan and Edo-Tokyo Museum. Growing area recognition from regular foreign tourist visits.",
         "feature_zh": "拥有国技馆及江户东京博物馆的文化区，外国游客定期到访使区域知名度持续上升。",
         "demand": "投資家・外国人居住者",
         "demand_en": "Investors, foreign residents",
         "demand_zh": "投资者・外国居民",
         "trend": "緩やかな上昇"},
        {"name": "向島", "name_en": "Mukōjima",
         "mansion": "90〜160万円/㎡", "land": "140〜220万円/㎡",
         "feature": "隅田川沿いの下町エリア。花火大会の名所として知名度が高く、水辺物件はプレミアムが乗る。",
         "feature_en": "Shitamachi area along Sumida River. Famous fireworks venue; waterfront properties command a premium.",
         "feature_zh": "隅田川沿线下町区域，以烟火大会胜地而知名，临水物件享有溢价。",
         "demand": "地元実需・投資家",
         "demand_en": "Local real demand, investors",
         "demand_zh": "本地实需・投资者",
         "trend": "緩やかな上昇"},
        {"name": "曳舟", "name_en": "Hikifune",
         "mansion": "100〜170万円/㎡", "land": "155〜240万円/㎡",
         "feature": "東武線沿線で利便性が高く、若年層の移住が増加中。リノベ需要も高く、物件価値が上昇傾向。",
         "feature_en": "High convenience along Tobu Line; young-generation migration increasing. Renovation demand is high; property values trending up.",
         "feature_zh": "东武线沿线便利性高，年轻层移居持续增加，改建需求旺盛，物件价值呈上涨趋势。",
         "demand": "若年層・投資家",
         "demand_en": "Young residents, investors",
         "demand_zh": "年轻层・投资者",
         "trend": "上昇"},
    ],
    "koto": [
        {"name": "豊洲", "name_en": "Toyosu",
         "mansion": "130〜230万円/㎡", "land": "200〜300万円/㎡",
         "feature": "市場移転後も商業・居住開発が続くエリア。都心直結の利便性で成約価格が継続上昇中。",
         "feature_en": "Commercial and residential development continues after the market relocation. Direct city access supports consistent price rises.",
         "feature_zh": "市场迁移后商业及住居开发仍持续，都心直连便利性支撑成交价格持续上涨。",
         "demand": "DINKs・ファミリー・投資家",
         "demand_en": "DINKs, families, investors",
         "demand_zh": "丁克族・家庭・投资者",
         "trend": "上昇"},
        {"name": "有明", "name_en": "Ariake",
         "mansion": "120〜210万円/㎡", "land": "190〜280万円/㎡",
         "feature": "五輪施設跡地の再開発が続く。広い専有面積の物件が多く、都心居住ファミリー需要が根強い。",
         "feature_en": "Redevelopment of Olympic facilities continues. Many large-format units; strong family demand for spacious city living.",
         "feature_zh": "奥运设施遗址再开发持续，大面积户型物件众多，都心居住家庭需求根深蒂固。",
         "demand": "外国人ファミリー・実需",
         "demand_en": "Foreign families, real demand buyers",
         "demand_zh": "外籍家庭・实需买方",
         "trend": "上昇"},
        {"name": "東雲", "name_en": "Shinonome",
         "mansion": "120〜200万円/㎡", "land": "180〜270万円/㎡",
         "feature": "大規模タワーが集積する再開発エリア。湾岸ビューの物件は希少価値から高値成約が多い。",
         "feature_en": "Large-scale tower concentration in redeveloping zone. Bay-view properties command premium closings from their scarcity value.",
         "feature_zh": "大规模塔楼集中的再开发区域，湾岸景观物件因稀缺价值高价成交案例多见。",
         "demand": "投資家・DINKs",
         "demand_en": "Investors, DINKs",
         "demand_zh": "投资者・丁克族",
         "trend": "上昇"},
        {"name": "門前仲町", "name_en": "Monzen-Nakachō",
         "mansion": "130〜220万円/㎡", "land": "200〜300万円/㎡",
         "feature": "富岡八幡宮の門前町として商業が充実。下町ブランドと利便性の両立で幅広い需要層がある。",
         "feature_en": "Vibrant commercial area fronting Tomioka Hachimangu. Shitamachi brand meets convenience; broad buyer appeal.",
         "feature_zh": "富冈八幡宫门前町商业充实，下町品牌与便利性兼备，吸引广泛需求层。",
         "demand": "ファミリー実需・投資家",
         "demand_en": "Families, investors",
         "demand_zh": "家庭实需・投资者",
         "trend": "安定上昇"},
        {"name": "亀戸", "name_en": "Kameido",
         "mansion": "100〜180万円/㎡", "land": "160〜250万円/㎡",
         "feature": "総武線で都心直結。価格が手頃で実需購入者が多く、適正価格での成約が取りやすいエリア。",
         "feature_en": "Direct Sōbu Line access to the city. Affordable prices; many genuine buyers; easy to achieve timely closings at fair price.",
         "feature_zh": "总武线直达都心，价格合理，实需购买者众多，合理定价可轻松实现成交。",
         "demand": "ファミリー実需・投資家",
         "demand_en": "Family real demand, investors",
         "demand_zh": "家庭实需・投资者",
         "trend": "緩やかな上昇"},
    ],
    "shinagawa": [
        {"name": "大崎", "name_en": "Ōsaki",
         "mansion": "160〜280万円/㎡", "land": "250〜380万円/㎡",
         "feature": "山手線で渋谷・新宿直通。リニア品川駅への近さから地価上昇が継続。法人社宅需要も厚い。",
         "feature_en": "Direct Yamanote Line to Shibuya and Shinjuku. Land prices keep rising due to proximity to Linear Shinagawa Station; strong corporate housing demand.",
         "feature_zh": "山手线直通涩谷、新宿，因临近磁悬浮品川站地价持续上涨，法人社宅需求旺盛。",
         "demand": "外資社宅・DINKs・投資家",
         "demand_en": "Foreign corporate housing, DINKs, investors",
         "demand_zh": "外资社宅・丁克族・投资者",
         "trend": "強い上昇"},
        {"name": "武蔵小山", "name_en": "Musashi-Koyama",
         "mansion": "140〜240万円/㎡", "land": "220〜350万円/㎡",
         "feature": "商店街が活発で生活利便性が高い人気エリア。住みたい街ランキング上位常連で、需要が安定して厚い。",
         "feature_en": "Popular area with active shopping street and high everyday convenience. Consistently high in 'places to live' rankings; steady strong demand.",
         "feature_zh": "商店街活跃、生活便利性高的人气区域，长期位居'最想居住街区'排名前列，需求稳定旺盛。",
         "demand": "ファミリー・若年実需",
         "demand_en": "Families, young real demand buyers",
         "demand_zh": "家庭・年轻实需",
         "trend": "上昇"},
        {"name": "旗の台", "name_en": "Hatanodai",
         "mansion": "130〜220万円/㎡", "land": "200〜320万円/㎡",
         "feature": "東急池上線・大井町線の乗換駅。複数路線沿線で利便性が高く、ファミリー実需が安定。",
         "feature_en": "Transfer station for Tokyu Ikegami and Ōimachi lines. Multi-line convenience supports stable family real demand.",
         "feature_zh": "东急池上线及大井町线换乘站，多线沿线便利性高，家庭实需稳定。",
         "demand": "ファミリー実需",
         "demand_en": "Family real demand buyers",
         "demand_zh": "家庭实需",
         "trend": "安定上昇"},
        {"name": "戸越", "name_en": "Togoshi",
         "mansion": "130〜220万円/㎡", "land": "200〜310万円/㎡",
         "feature": "戸越銀座商店街を擁する生活感あるエリア。実需購入者が多く、適正価格設定で早期成約が狙える。",
         "feature_en": "Everyday residential area with Togoshi Ginza shopping street. Many genuine buyers; correct pricing enables early closing.",
         "feature_zh": "拥有户越银座商店街的生活气息浓厚区域，实需购买者众多，合理定价可实现早期成交。",
         "demand": "ファミリー・子育て世代",
         "demand_en": "Families, child-rearing generation",
         "demand_zh": "家庭・育儿世代",
         "trend": "安定"},
        {"name": "西五反田", "name_en": "Nishi-Gotanda",
         "mansion": "150〜260万円/㎡", "land": "230〜360万円/㎡",
         "feature": "五反田再開発の恩恵を受けるエリア。IT系企業集積で単身ビジネス層の賃貸需要が厚い。",
         "feature_en": "Benefits from Gotanda redevelopment. IT firm concentration drives strong rental demand from single business workers.",
         "feature_zh": "受益于五反田再开发，IT企业集聚带动单身商务层租赁需求旺盛。",
         "demand": "IT系ビジネス層・投資家",
         "demand_en": "IT sector business workers, investors",
         "demand_zh": "IT系商务层・投资者",
         "trend": "上昇"},
    ],
    "meguro": [
        {"name": "中目黒", "name_en": "Naka-Meguro",
         "mansion": "200〜340万円/㎡", "land": "300〜480万円/㎡",
         "feature": "目黒川沿いの最人気エリア。桜シーズンは全国的な注目を集め、外国人富裕層の購入が増加中。",
         "feature_en": "Most popular area along Meguro River. Cherry blossom season draws national attention; affluent foreign buyers are increasing.",
         "feature_zh": "目黒川沿线最人气区域，樱花季吸引全国目光，外国富裕层购买持续增加。",
         "demand": "外国人富裕層・クリエイター",
         "demand_en": "Affluent foreign buyers, creatives",
         "demand_zh": "外国富裕层・创意人士",
         "trend": "強い上昇"},
        {"name": "自由が丘", "name_en": "Jiyūgaoka",
         "mansion": "190〜320万円/㎡", "land": "280〜450万円/㎡",
         "feature": "スイーツ・ファッションの聖地として全国区のブランド。遠方からの移住者が多く、高値でも成約しやすい。",
         "feature_en": "Nationally branded as a sweets and fashion destination. Many buyers relocating from afar; easy to achieve high-price closings.",
         "feature_zh": "以甜点及时尚圣地享誉全国，来自远方的移居者众多，即便高价也易于成交。",
         "demand": "全国移住者・富裕ファミリー",
         "demand_en": "Buyers relocating nationwide, affluent families",
         "demand_zh": "全国移居者・富裕家庭",
         "trend": "上昇"},
        {"name": "学芸大学", "name_en": "Gakugei-Daigaku",
         "mansion": "170〜280万円/㎡", "land": "250〜400万円/㎡",
         "feature": "住みたい街ランキング上位常連。落ち着いた環境と商業の共存でファミリー需要が非常に安定。",
         "feature_en": "Consistently high in 'places to live' rankings. Calm environment and commercial mix supports very stable family demand.",
         "feature_zh": "长期位居'最想居住街区'排名前列，宁静环境与商业共存，家庭需求极为稳定。",
         "demand": "ファミリー・子育て世代",
         "demand_en": "Families, child-rearing generation",
         "demand_zh": "家庭・育儿世代",
         "trend": "安定上昇"},
        {"name": "祐天寺", "name_en": "Yūtenji",
         "mansion": "160〜270万円/㎡", "land": "240〜380万円/㎡",
         "feature": "中目黒に隣接しながら比較的手頃。「中目黒隣接」として売り出すことで価格アップが狙える。",
         "feature_en": "Adjacent to Naka-Meguro yet relatively affordable. Marketing as 'adjacent to Naka-Meguro' can push the price higher.",
         "feature_zh": "毗邻中目黒但价格相对合理，以'中目黒邻接'为卖点可争取更高价格。",
         "demand": "中目黒志向ファミリー・投資家",
         "demand_en": "Naka-Meguro-oriented families, investors",
         "demand_zh": "中目黒志向家庭・投资者",
         "trend": "上昇"},
        {"name": "目黒本町", "name_en": "Meguro-Honchō",
         "mansion": "150〜250万円/㎡", "land": "230〜360万円/㎡",
         "feature": "目黒区内で比較的手頃な価格帯。駒沢公園へのアクセスも良く、自然環境を重視するファミリー需要がある。",
         "feature_en": "Relatively affordable within Meguro-ku. Good access to Komazawa Park; nature-conscious family demand.",
         "feature_zh": "在目黒区内价格相对合理，通往驹泽公园便利，重视自然环境的家庭需求旺盛。",
         "demand": "ファミリー実需",
         "demand_en": "Family real demand buyers",
         "demand_zh": "家庭实需",
         "trend": "安定上昇"},
    ],
    "ota": [
        {"name": "田園調布", "name_en": "Denenchōfu",
         "mansion": "250〜400万円/㎡", "land": "400〜700万円/㎡",
         "feature": "日本最高水準の高級住宅地。芸能人・経営者が多く居住し、供給が少ないため出れば必ず引き合いがある。",
         "feature_en": "Japan's top-tier premium residential area. Home to many entertainers and executives; very limited supply means every listing draws competing inquiries.",
         "feature_zh": "日本最高水准高级住宅地，众多演艺人士及企业主居住，供给稀少，每次上市必有多方问询。",
         "demand": "富裕層・芸能人・経営者",
         "demand_en": "Affluent buyers, celebrities, business owners",
         "demand_zh": "富裕层・演艺人士・企业主",
         "trend": "強い上昇"},
        {"name": "多摩川", "name_en": "Tamagawa",
         "mansion": "160〜270万円/㎡", "land": "240〜400万円/㎡",
         "feature": "多摩川沿いの緑豊かな住環境。川沿いの眺望物件はプレミアムが乗り、通常より高値での成約が期待できる。",
         "feature_en": "Green residential environment along Tamagawa River. Riverside view properties carry a premium; above-market closings are expected.",
         "feature_zh": "多摩川沿线绿意盎然的居住环境，川畔景观物件享有溢价，可期待高于通常水平的成交价格。",
         "demand": "富裕ファミリー・自然志向層",
         "demand_en": "Affluent families, nature-oriented buyers",
         "demand_zh": "富裕家庭・自然志向层",
         "trend": "上昇"},
        {"name": "大森", "name_en": "Ōmori",
         "mansion": "110〜190万円/㎡", "land": "180〜280万円/㎡",
         "feature": "羽田空港へのアクセスが良好。国際線拡充で外国人ビジネスマンの居住需求が増加中。",
         "feature_en": "Good access to Haneda Airport. Expanding international routes are increasing foreign business resident demand.",
         "feature_zh": "羽田机场可达性优良，国际航线扩充带动外国商务人士居住需求持续增加。",
         "demand": "外国人ビジネス層・ファミリー",
         "demand_en": "Foreign business workers, families",
         "demand_zh": "外国商务层・家庭",
         "trend": "上昇"},
        {"name": "蒲田", "name_en": "Kamata",
         "mansion": "100〜170万円/㎡", "land": "170〜260万円/㎡",
         "feature": "東急・京急2路線で羽田・渋谷直通。価格帯が手頃で投資利回りが取りやすく、投資家需要が安定。",
         "feature_en": "Direct Tokyu and Keikyu access to Haneda and Shibuya. Affordable price point makes yield investing easy; stable investor demand.",
         "feature_zh": "东急、京急两线直通羽田及涩谷，价格合理易于获取投资收益，投资者需求稳定。",
         "demand": "投資家・実需購入者",
         "demand_en": "Investors, real demand buyers",
         "demand_zh": "投资者・实需购买者",
         "trend": "緩やかな上昇"},
        {"name": "久が原", "name_en": "Kugahara",
         "mansion": "130〜220万円/㎡", "land": "200〜320万円/㎡",
         "feature": "田園調布隣接の高級住宅地。田園調布ブランドの波及効果で価格が上昇傾向にある。",
         "feature_en": "Premium residential area adjacent to Denenchōfu. The Denenchōfu brand spillover is lifting prices.",
         "feature_zh": "毗邻田园调布的高级住宅地，田园调布品牌的溢出效应带动价格呈上涨趋势。",
         "demand": "富裕ファミリー・住み替え層",
         "demand_en": "Affluent families, move-up buyers",
         "demand_zh": "富裕家庭・换购层",
         "trend": "上昇"},
    ],
    "setagaya": [
        {"name": "二子玉川", "name_en": "Futako-Tamagawa",
         "mansion": "180〜300万円/㎡", "land": "280〜420万円/㎡",
         "feature": "高感度商業施設と多摩川の自然環境が共存。全国的な知名度から遠方移住者が多く、高値成約が続く。",
         "feature_en": "Upscale commercial facilities coexist with the natural Tamagawa environment. National name recognition brings many buyers from afar; high-price closings continue.",
         "feature_zh": "高品位商业设施与多摩川自然环境共存，全国知名度吸引远方移居者众多，高价成交持续。",
         "demand": "富裕ファミリー・全国移住者",
         "demand_en": "Affluent families, buyers relocating from around Japan",
         "demand_zh": "富裕家庭・全国移居者",
         "trend": "強い上昇"},
        {"name": "成城", "name_en": "Seijō",
         "mansion": "200〜340万円/㎡", "land": "300〜500万円/㎡",
         "feature": "芸能人・著名人が多く住む最高格住宅地。「成城」の住所ブランドが価格に明確な上乗せをもたらす。",
         "feature_en": "Top-tier residential area famous for entertainers and celebrities. The 'Seijō' address brand adds a verifiable price premium.",
         "feature_zh": "众多演艺人士及著名人士居住的最高格住宅地，'成城'地址品牌为价格带来明确的附加溢价。",
         "demand": "富裕層・著名人・経営者",
         "demand_en": "Affluent buyers, celebrities, business owners",
         "demand_zh": "富裕层・著名人士・企业主",
         "trend": "上昇"},
        {"name": "三軒茶屋", "name_en": "Sangenjaya",
         "mansion": "160〜270万円/㎡", "land": "250〜380万円/㎡",
         "feature": "若年層に高い人気のエリア。下北沢・渋谷への好アクセスで賃貸需要が厚く、投資物件の利回りが取りやすい。",
         "feature_en": "Highly popular with young buyers. Good access to Shimokitazawa and Shibuya; thick rental demand supports investment property yields.",
         "feature_zh": "深受年轻层欢迎，通往下北泽及涩谷便捷，租赁需求旺盛，投资物件收益易于获取。",
         "demand": "若年富裕層・投資家",
         "demand_en": "Young affluent buyers, investors",
         "demand_zh": "年轻富裕层・投资者",
         "trend": "上昇"},
        {"name": "下北沢", "name_en": "Shimokitazawa",
         "mansion": "150〜260万円/㎡", "land": "230〜360万円/㎡",
         "feature": "音楽・演劇の文化エリアとして独自ブランドを確立。小田急線再開発後の価値向上が続いている。",
         "feature_en": "Established unique brand as a music and theater cultural area. Post-Odakyu redevelopment value appreciation continues.",
         "feature_zh": "作为音乐及戏剧文化区确立了独特品牌，小田急线再开发后价值提升仍在持续。",
         "demand": "クリエイター・若年層",
         "demand_en": "Creatives, young residents",
         "demand_zh": "创意人士・年轻层",
         "trend": "上昇"},
        {"name": "千歳烏山", "name_en": "Chitose-Karasuyama",
         "mansion": "130〜220万円/㎡", "land": "200〜310万円/㎡",
         "feature": "京王線で新宿直通。世田谷区内では手頃な価格帯で、ファミリー実需が安定している。",
         "feature_en": "Direct Keio Line to Shinjuku. Affordable within Setagaya; stable family real demand.",
         "feature_zh": "京王线直达新宿，在世田谷区内价格合理，家庭实需稳定。",
         "demand": "ファミリー実需・投資家",
         "demand_en": "Family real demand, investors",
         "demand_zh": "家庭实需・投资者",
         "trend": "安定上昇"},
    ],
    "shibuya": [
        {"name": "代官山", "name_en": "Daikanyama",
         "mansion": "280〜420万円/㎡", "land": "350〜550万円/㎡",
         "feature": "洗練されたショップ・カフェが集積する国際的エリア。外国人富裕層・クリエイター層の居住需要が高く、外資ネットワーク経由の売却実績が豊富。",
         "feature_en": "International area with sophisticated shops and cafes. High residential demand from affluent foreign buyers and creatives; rich track record of foreign-network sales.",
         "feature_zh": "汇聚精致商店及咖啡馆的国际区域，外国富裕层及创意层居住需求旺盛，通过外资网络出售的实绩丰富。",
         "demand": "外国人富裕層・クリエイター",
         "demand_en": "Affluent foreign buyers, creatives",
         "demand_zh": "外国富裕层・创意人士",
         "trend": "強い上昇"},
        {"name": "広尾", "name_en": "Hiroo",
         "mansion": "250〜380万円/㎡", "land": "300〜500万円/㎡",
         "feature": "大使館街隣接で外国人居住者が多い。外国語スクール・インターナショナルスクールが充実し、外国人ファミリーの定住需要が非常に厚い。",
         "feature_en": "Many foreign residents due to embassy district adjacency. International schools plentiful; very deep foreign family settlement demand.",
         "feature_zh": "毗邻大使馆街，外国居民众多，国际学校充实，外籍家庭定居需求极为旺盛。",
         "demand": "外国人富裕層・大使館関係者",
         "demand_en": "Affluent foreign buyers, embassy-related residents",
         "demand_zh": "外国富裕层・大使馆相关人士",
         "trend": "上昇"},
        {"name": "恵比寿", "name_en": "Ebisu",
         "mansion": "230〜350万円/㎡", "land": "280〜450万円/㎡",
         "feature": "恵比寿ガーデンプレイスを中心とした高感度エリア。外資系企業勤務者の居住需要が厚く、法人社宅取引も多い。",
         "feature_en": "High-profile area centered on Ebisu Garden Place. Thick demand from foreign company workers; many corporate housing transactions.",
         "feature_zh": "以惠比寿花园广场为中心的高品位区域，外资企业员工居住需求旺盛，法人社宅交易亦多见。",
         "demand": "外資社宅・富裕層・DINKs",
         "demand_en": "Foreign corporate housing, affluent buyers, DINKs",
         "demand_zh": "外资社宅・富裕层・丁克族",
         "trend": "上昇"},
        {"name": "松濤", "name_en": "Shōtō",
         "mansion": "300〜500万円/㎡", "land": "400〜700万円/㎡",
         "feature": "渋谷区最高格の住宅地。芸能人・実業家が多く居住し、供給が極めて少ない。出せば必ず高値の引き合いが来る。",
         "feature_en": "Shibuya's most prestigious residential area. Many entertainers and entrepreneurs; extremely limited supply — premium inquiries guaranteed every listing.",
         "feature_zh": "涩谷区最高格住宅地，众多演艺人士及实业家居住，供给极度稀缺，每次上市必有高价问询。",
         "demand": "富裕層・著名人・実業家",
         "demand_en": "Affluent buyers, celebrities, entrepreneurs",
         "demand_zh": "富裕层・著名人士・企业家",
         "trend": "強い上昇"},
        {"name": "神宮前", "name_en": "Jingūmae",
         "mansion": "200〜320万円/㎡", "land": "280〜420万円/㎡",
         "feature": "原宿・表参道の心臓部。外国人観光客・ファッション業界人の集積エリアで、商業・居住双方の出口が取れる。",
         "feature_en": "Heart of Harajuku and Omotesandō. Concentration of foreign tourists and fashion industry; both residential and commercial exits available.",
         "feature_zh": "原宿、表参道的核心地带，外国游客及时尚业界人士集聚，可同时实现商业及住居两种出口方式。",
         "demand": "ファッション業界人・外国人投資家",
         "demand_en": "Fashion industry buyers, foreign investors",
         "demand_zh": "时尚业界人士・外国投资者",
         "trend": "上昇"},
    ],
    "nakano": [
        {"name": "中野", "name_en": "Nakano",
         "mansion": "140〜230万円/㎡", "land": "220〜340万円/㎡",
         "feature": "中野駅周辺の大規模再開発が進行中。新たな商業・オフィス施設の整備でエリア価値が上昇している。",
         "feature_en": "Large-scale redevelopment of Nakano Station area in progress. New commercial and office facilities are lifting area value.",
         "feature_zh": "中野站周边大规模再开发进行中，新商业及办公设施的整备带动区域价值上升。",
         "demand": "ビジネス層・投資家・ファミリー",
         "demand_en": "Business workers, investors, families",
         "demand_zh": "商务层・投资者・家庭",
         "trend": "再開発期待で上昇"},
        {"name": "野方", "name_en": "Nogata",
         "mansion": "120〜200万円/㎡", "land": "190〜300万円/㎡",
         "feature": "西武新宿線沿線の住宅エリア。手頃な価格帯で生活利便性が高く、ファミリー実需が安定している。",
         "feature_en": "Residential area along Seibu Shinjuku Line. Affordable with high everyday convenience; stable family real demand.",
         "feature_zh": "西武新宿线沿线住宅区，价格合理、生活便利性高，家庭实需稳定。",
         "demand": "ファミリー実需",
         "demand_en": "Family real demand",
         "demand_zh": "家庭实需",
         "trend": "緩やかな上昇"},
        {"name": "鷺宮", "name_en": "Saginomiya",
         "mansion": "110〜190万円/㎡", "land": "180〜280万円/㎡",
         "feature": "閑静な住宅地として知られるエリア。中野区内でも落ち着いた環境で、戸建て相続案件が多い。",
         "feature_en": "Known as a quiet residential area. Calm environment even within Nakano-ku; many detached house inheritance cases.",
         "feature_zh": "以宁静住宅地著称，在中野区内也属安静环境，独栋住宅继承案件多见。",
         "demand": "ファミリー実需・地元住み替え",
         "demand_en": "Family real demand, local move-up buyers",
         "demand_zh": "家庭实需・本地换购",
         "trend": "安定"},
        {"name": "弥生町", "name_en": "Yayoichō",
         "mansion": "130〜210万円/㎡", "land": "200〜310万円/㎡",
         "feature": "中野区中央に位置し交通利便性が高い。中野駅再開発の波及効果を受けるエリアとして注目度が上昇。",
         "feature_en": "Centrally located in Nakano-ku with excellent transit. Rising attention as an area set to benefit from Nakano Station redevelopment spillover.",
         "feature_zh": "位于中野区中央，交通便利性高，作为受益于中野站再开发溢出效应的区域关注度上升。",
         "demand": "ファミリー・投資家",
         "demand_en": "Families, investors",
         "demand_zh": "家庭・投资者",
         "trend": "上昇"},
        {"name": "新井", "name_en": "Arai",
         "mansion": "130〜220万円/㎡", "land": "200〜320万円/㎡",
         "feature": "新井薬師エリアで商店街が活発。中野駅・沼袋駅の両方にアクセスでき、生活利便性が高い。",
         "feature_en": "Active shopping area near Araiyakushi. Access to both Nakano and Numabukuro stations; high everyday convenience.",
         "feature_zh": "新井药师周边商店街活跃，可通达中野站及沼袋站，生活便利性高。",
         "demand": "ファミリー実需・投資家",
         "demand_en": "Family real demand, investors",
         "demand_zh": "家庭实需・投资者",
         "trend": "緩やかな上昇"},
    ],
    "suginami": [
        {"name": "荻窪", "name_en": "Ogikubo",
         "mansion": "120〜210万円/㎡", "land": "190〜300万円/㎡",
         "feature": "JR中央線・東京メトロ2路線が通る交通の要衝。生活利便性が高く、都心通勤層のファミリー需要が安定している。",
         "feature_en": "Transit nexus with JR Chūō Line and two Tokyo Metro lines. High everyday convenience; stable family commuter demand.",
         "feature_zh": "JR中央线及东京地铁两条线路的交通要冲，生活便利性高，都心通勤家庭需求稳定。",
         "demand": "ファミリー・DINKs実需",
         "demand_en": "Families, DINKs real demand",
         "demand_zh": "家庭・丁克族实需",
         "trend": "安定上昇"},
        {"name": "高円寺", "name_en": "Kōenji",
         "mansion": "120〜200万円/㎡", "land": "185〜290万円/㎡",
         "feature": "古着・ライブ・カルチャーで独自ブランドを確立。クリエイター・アーティストの移住先として根強い人気がある。",
         "feature_en": "Established unique brand through vintage clothing, live music, and culture. Persistent popularity as a destination for creator and artist migration.",
         "feature_zh": "凭借古着、现场音乐及文化建立了独特品牌，作为创意人士及艺术家的移居目的地人气持久。",
         "demand": "クリエイター・若年層",
         "demand_en": "Creatives, young residents",
         "demand_zh": "创意人士・年轻层",
         "trend": "上昇"},
        {"name": "阿佐ヶ谷", "name_en": "Asagaya",
         "mansion": "110〜190万円/㎡", "land": "175〜280万円/㎡",
         "feature": "七夕まつりで有名な商店街エリア。落ち着いた住環境と商業の共存でファミリー移住者が増加中。",
         "feature_en": "Shopping street area famous for Tanabata Festival. Calm living environment alongside commercial activity; family migrants increasing.",
         "feature_zh": "以七夕祭著名的商店街区域，宁静居住环境与商业共存，家庭移居者持续增加。",
         "demand": "ファミリー実需",
         "demand_en": "Family real demand",
         "demand_zh": "家庭实需",
         "trend": "安定上昇"},
        {"name": "西荻窪", "name_en": "Nishi-Ogikubo",
         "mansion": "115〜195万円/㎡", "land": "180〜285万円/㎡",
         "feature": "アンティーク・古書店が集まる個性派エリア。独自の文化圏が形成されており、エリアブランドが価格に乗る。",
         "feature_en": "Distinctive area with antique shops and used bookstores. An autonomous cultural zone has formed; the area brand layers onto pricing.",
         "feature_zh": "古董店及旧书店云集的个性派区域，独自的文化圈已形成，区域品牌叠加于价格之上。",
         "demand": "個性派富裕層・クリエイター",
         "demand_en": "Distinctive affluent buyers, creatives",
         "demand_zh": "个性派富裕层・创意人士",
         "trend": "上昇"},
        {"name": "永福", "name_en": "Eifuku",
         "mansion": "100〜175万円/㎡", "land": "160〜260万円/㎡",
         "feature": "杉並区内でも比較的手頃なエリア。広い一戸建てが多く、相続・住み替え案件での売却が多い。",
         "feature_en": "Relatively affordable even within Suginami. Many large detached homes; frequent inheritance and move-up sale cases.",
         "feature_zh": "在杉并区内也属价格相对合理区域，大型独栋住宅众多，继承及换购出售案件多见。",
         "demand": "ファミリー実需・地元住み替え",
         "demand_en": "Family real demand, local move-up buyers",
         "demand_zh": "家庭实需・本地换购",
         "trend": "緩やかな上昇"},
    ],
    "toshima": [
        {"name": "池袋", "name_en": "Ikebukuro",
         "mansion": "110〜190万円/㎡", "land": "180〜280万円/㎡",
         "feature": "大規模再開発進行中で急成長するエリア。外国人居住者が多く、外語対応物件の需要が強い。",
         "feature_en": "Fast-growing area with large-scale redevelopment underway. Many foreign residents; strong demand for multilingual-friendly properties.",
         "feature_zh": "大规模再开发进行中的快速成长区域，外国居民众多，外语对应物件需求强劲。",
         "demand": "外国人・投資家・単身ビジネス層",
         "demand_en": "Foreign residents, investors, single business workers",
         "demand_zh": "外国居民・投资者・单身商务层",
         "trend": "再開発期待で上昇"},
        {"name": "目白", "name_en": "Mejiro",
         "mansion": "140〜240万円/㎡", "land": "220〜350万円/㎡",
         "feature": "学習院大学隣接の落ち着いた高級住宅地。文教ブランドから富裕層・高齢富裕層の定住需要が根強い。",
         "feature_en": "Quiet premium residential area adjacent to Gakushuin University. Academic brand drives deep demand from affluent buyers and wealthy older residents.",
         "feature_zh": "毗邻学习院大学的宁静高级住宅地，文教品牌带来富裕层及高龄富裕层的根深蒂固定居需求。",
         "demand": "富裕層・高齢富裕層",
         "demand_en": "Affluent buyers, wealthy older residents",
         "demand_zh": "富裕层・高龄富裕层",
         "trend": "安定上昇"},
        {"name": "巣鴨", "name_en": "Sugamo",
         "mansion": "120〜200万円/㎡", "land": "190〜300万円/㎡",
         "feature": "「おばあちゃんの原宿」として知名度が高い商店街エリア。高齢富裕層の相続案件が多く、価格設定次第で大きく変わる。",
         "feature_en": "Shopping street area nationally known as 'grandma's Harajuku.' Many inheritance cases from wealthy older residents; outcome depends heavily on pricing strategy.",
         "feature_zh": "以'老奶奶的原宿'闻名全国的商店街区域，高龄富裕层继承案件多，结果很大程度取决于定价策略。",
         "demand": "高齢富裕層・相続案件",
         "demand_en": "Wealthy older buyers, inheritance cases",
         "demand_zh": "高龄富裕层・继承案例",
         "trend": "安定"},
        {"name": "駒込", "name_en": "Komagome",
         "mansion": "130〜210万円/㎡", "land": "200〜310万円/㎡",
         "feature": "山手線沿線で六義園・旧古河庭園など緑地が豊富。都心への利便性と自然環境を兼備する人気住宅地。",
         "feature_en": "Yamanote Line; abundant greenery including Rikugien and Furukawa Garden. Popular residential area balancing city access and natural environment.",
         "feature_zh": "山手线沿线，六义园、旧古河庭园等绿地丰富，兼具都心便利性与自然环境的人气住宅地。",
         "demand": "ファミリー・自然志向層",
         "demand_en": "Families, nature-oriented buyers",
         "demand_zh": "家庭・自然志向层",
         "trend": "安定上昇"},
        {"name": "雑司が谷", "name_en": "Zōshigaya",
         "mansion": "120〜200万円/㎡", "land": "190〜290万円/㎡",
         "feature": "都電荒川線とメトロ副都心線が通る利便性の高いエリア。静かな住環境が再評価されており、需要が増加中。",
         "feature_en": "Served by Toden Arakawa Line and Metro Fukutoshin Line. Quiet residential environment is being re-evaluated; demand increasing.",
         "feature_zh": "都电荒川线及地铁副都心线贯穿，宁静的居住环境正被重新评价，需求持续增加。",
         "demand": "ファミリー・若年層",
         "demand_en": "Families, young residents",
         "demand_zh": "家庭・年轻层",
         "trend": "上昇"},
    ],
    "kita": [
        {"name": "赤羽", "name_en": "Akabane",
         "mansion": "100〜180万円/㎡", "land": "160〜260万円/㎡",
         "feature": "住みたい街ランキングで急上昇中。JR複数路線で都心直通、飲食・商業が充実した人気エリア。",
         "feature_en": "Rapidly rising in 'most desired neighborhoods' rankings. Multiple JR lines to city center; rich dining and commercial scene.",
         "feature_zh": "'最想居住街区'排名急速上升，JR多条线路直达都心，饮食及商业设施充实的人气区域。",
         "demand": "ファミリー・全国移住者",
         "demand_en": "Families, buyers relocating from around Japan",
         "demand_zh": "家庭・全国移居者",
         "trend": "上昇"},
        {"name": "王子", "name_en": "Ōji",
         "mansion": "95〜160万円/㎡", "land": "150〜240万円/㎡",
         "feature": "飛鳥山公園を擁する緑豊かなエリア。都心に近い割に価格が手頃で、投資家の利回り需要が安定。",
         "feature_en": "Green area with Asukayama Park. Affordable relative to its city proximity; stable yield-focused investor demand.",
         "feature_zh": "拥有飞鸟山公园的绿意盎然区域，相对都心近距离而言价格合理，投资者利回需求稳定。",
         "demand": "ファミリー実需・投資家",
         "demand_en": "Family real demand, investors",
         "demand_zh": "家庭实需・投资者",
         "trend": "緩やかな上昇"},
        {"name": "十条", "name_en": "Jūjō",
         "mansion": "100〜170万円/㎡", "land": "160〜250万円/㎡",
         "feature": "昔ながらの商店街が健在な生活感あるエリア。実需型購入者が多く、手頃な価格で早期成約が狙える。",
         "feature_en": "Authentic shopping street with shitamachi character still thriving. Many genuine buyers; achievable fast closing at fair price.",
         "feature_zh": "昔日风情商店街依然健在的生活气息浓厚区域，实需型购买者众多，价格合理可实现早期成交。",
         "demand": "ファミリー実需",
         "demand_en": "Family real demand",
         "demand_zh": "家庭实需",
         "trend": "安定"},
        {"name": "田端", "name_en": "Tabata",
         "mansion": "110〜180万円/㎡", "land": "170〜260万円/㎡",
         "feature": "JR山手線・京浜東北線沿線で交通利便性が高い。文京区・荒川区へのアクセスも良く、幅広い実需が安定。",
         "feature_en": "Served by JR Yamanote and Keihintōhoku lines. Good access to Bunkyo and Arakawa; broad and stable real demand.",
         "feature_zh": "JR山手线及京浜东北线沿线，交通便利性高，通往文京区及荒川区便捷，广泛的实需稳定。",
         "demand": "ファミリー実需・投資家",
         "demand_en": "Family real demand, investors",
         "demand_zh": "家庭实需・投资者",
         "trend": "緩やかな上昇"},
        {"name": "上中里", "name_en": "Kaminakazato",
         "mansion": "120〜200万円/㎡", "land": "190〜290万円/㎡",
         "feature": "北区の中でも比較的高価格帯の閑静な住宅地。滝野川などの自然環境が豊富で、落ち着いた環境需要がある。",
         "feature_en": "Quiet residential area at the higher end of Kita-ku pricing. Abundant natural environment including Takinogawa; demand for calm surroundings.",
         "feature_zh": "在北区属价格相对较高的宁静住宅地，泷野川等自然环境丰富，追求安静环境的需求旺盛。",
         "demand": "富裕ファミリー・高齢層",
         "demand_en": "Affluent families, older residents",
         "demand_zh": "富裕家庭・高龄层",
         "trend": "安定"},
    ],
    "arakawa": [
        {"name": "南千住", "name_en": "Minami-Senju",
         "mansion": "100〜175万円/㎡", "land": "160〜255万円/㎡",
         "feature": "つくばエクスプレスで秋葉原直通。再開発が進むエリアで、IT系ビジネス層の賃貸需要が急増中。",
         "feature_en": "Direct Tsukuba Express to Akihabara. Redeveloping area; rapidly growing IT business rental demand.",
         "feature_zh": "筑波快线直达秋叶原，再开发推进中，IT系商务层租赁需求急速增加。",
         "demand": "IT系ビジネス層・投資家",
         "demand_en": "IT sector business workers, investors",
         "demand_zh": "IT系商务层・投资者",
         "trend": "上昇"},
        {"name": "三河島", "name_en": "Mikawashima",
         "mansion": "95〜165万円/㎡", "land": "150〜240万円/㎡",
         "feature": "JR常磐線沿線で上野・新宿直通。価格が手頃で投資利回りが取りやすく、投資家需要が安定している。",
         "feature_en": "JR Jōban Line with direct access to Ueno and Shinjuku. Affordable with easy investment yields; stable investor demand.",
         "feature_zh": "JR常磐线沿线直达上野及新宿，价格合理、投资收益易于获取，投资者需求稳定。",
         "demand": "投資家・地元実需",
         "demand_en": "Investors, local real demand",
         "demand_zh": "投资者・本地实需",
         "trend": "緩やかな上昇"},
        {"name": "日暮里", "name_en": "Nippori",
         "mansion": "105〜175万円/㎡", "land": "165〜255万円/㎡",
         "feature": "問屋街・繊維街で商業価値が高い。成田空港直通（スカイライナー）の利便性で外国人居住者も多い。",
         "feature_en": "High commercial value from wholesale textile district. Narita Airport access via Skyliner attracts many foreign residents.",
         "feature_zh": "批发街及纺织街商业价值高，成田机场直连（Sky Liner）便利性吸引众多外国居民。",
         "demand": "外国人居住者・投資家",
         "demand_en": "Foreign residents, investors",
         "demand_zh": "外国居民・投资者",
         "trend": "上昇"},
        {"name": "西日暮里", "name_en": "Nishi-Nippori",
         "mansion": "110〜180万円/㎡", "land": "170〜260万円/㎡",
         "feature": "JR・メトロ・都電3路線が通る交通の要衝。東大・農工大が近く、学生・研究者需要が安定している。",
         "feature_en": "Transit nexus with JR, Metro, and Toden lines. UTokyo and TUAT nearby; stable student and researcher demand.",
         "feature_zh": "JR、地铁、都电三线交汇的交通要冲，东大及农工大毗邻，学生及研究者需求稳定。",
         "demand": "学生・研究者・投資家",
         "demand_en": "Students, researchers, investors",
         "demand_zh": "学生・研究者・投资者",
         "trend": "上昇"},
        {"name": "荒川", "name_en": "Arakawa",
         "mansion": "90〜155万円/㎡", "land": "140〜220万円/㎡",
         "feature": "都電荒川線（さくらトラム）沿線でレトロな雰囲気が人気。下町ブランドの再評価で値上がり余地が大きい。",
         "feature_en": "Along Toden Arakawa Line (Sakura Tram); popular retro atmosphere. Large upside as shitamachi brand is re-evaluated.",
         "feature_zh": "都电荒川线（樱花电车）沿线，复古氛围深受欢迎，随下町品牌再评价，价格上涨空间大。",
         "demand": "地元実需・下町ファン層",
         "demand_en": "Local real demand, shitamachi enthusiasts",
         "demand_zh": "本地实需・下町爱好者",
         "trend": "緩やかな上昇"},
    ],
    "itabashi": [
        {"name": "大山", "name_en": "Ōyama",
         "mansion": "95〜165万円/㎡", "land": "155〜245万円/㎡",
         "feature": "商店街が活発で生活利便性が高い。若年ファミリーの移住が増加しており、エリアの活気が増している。",
         "feature_en": "Active shopping street and high everyday convenience. Young family migration increasing; area growing more vibrant.",
         "feature_zh": "商店街活跃、生活便利性高，年轻家庭移居持续增加，区域活力不断提升。",
         "demand": "ファミリー実需・若年層",
         "demand_en": "Family real demand, young residents",
         "demand_zh": "家庭实需・年轻层",
         "trend": "上昇"},
        {"name": "常盤台", "name_en": "Tokiwadai",
         "mansion": "100〜170万円/㎡", "land": "160〜250万円/㎡",
         "feature": "板橋区内の高級住宅地として定評がある。閑静な環境と東武東上線の利便性でファミリー需要が安定。",
         "feature_en": "Established reputation as a premium residential area within Itabashi. Quiet environment and Tobu Tōjō Line convenience; stable family demand.",
         "feature_zh": "在板桥区内以高级住宅地著称，宁静环境与东武东上线便利性兼备，家庭需求稳定。",
         "demand": "ファミリー実需・子育て世代",
         "demand_en": "Family real demand, child-rearing generation",
         "demand_zh": "家庭实需・育儿世代",
         "trend": "安定上昇"},
        {"name": "成増", "name_en": "Narimasu",
         "mansion": "90〜155万円/㎡", "land": "145〜230万円/㎡",
         "feature": "東武東上線・有楽町線2路線が通り、池袋・都心直通。手頃な価格帯で投資利回りが取りやすい。",
         "feature_en": "Served by Tobu Tōjō Line and Yurakucho Line; direct access to Ikebukuro and city. Affordable price range makes investment yields achievable.",
         "feature_zh": "东武东上线及有乐町线两线贯穿，直达池袋及都心，价格合理、投资收益易于获取。",
         "demand": "投資家・ファミリー実需",
         "demand_en": "Investors, family real demand",
         "demand_zh": "投资者・家庭实需",
         "trend": "安定"},
        {"name": "高島平", "name_en": "Takashimadaira",
         "mansion": "80〜140万円/㎡", "land": "130〜210万円/㎡",
         "feature": "大規模団地の再開発計画が浮上中。再開発が正式決定すれば価格が急騰する可能性があり、今が売却適正タイミング。",
         "feature_en": "Large-scale housing complex redevelopment under consideration. Formal decision could trigger a sharp price increase — now may be the right exit timing.",
         "feature_zh": "大规模团地再开发计划浮出水面，若正式决定将可能触发价格急涨，现在是出售的适当时机。",
         "demand": "投資家・再開発期待層",
         "demand_en": "Investors, redevelopment expectation buyers",
         "demand_zh": "投资者・再开发期待层",
         "trend": "再開発期待で上昇"},
        {"name": "志村", "name_en": "Shimura",
         "mansion": "85〜150万円/㎡", "land": "140〜220万円/㎡",
         "feature": "都営三田線沿線で都心直通。板橋区内で比較的手頃な価格帯で、ファミリー実需が安定している。",
         "feature_en": "Served by Toei Mita Line with direct access to city. Relatively affordable within Itabashi; stable family real demand.",
         "feature_zh": "都营三田线沿线直达都心，在板桥区内价格相对合理，家庭实需稳定。",
         "demand": "ファミリー実需",
         "demand_en": "Family real demand",
         "demand_zh": "家庭实需",
         "trend": "安定"},
    ],
    "nerima": [
        {"name": "石神井公園", "name_en": "Shakujii-Kōen",
         "mansion": "90〜155万円/㎡", "land": "145〜235万円/㎡",
         "feature": "石神井公園隣接で23区内でも希少な豊かな自然環境。公園隣接物件はプレミアムが付きやすく、高値成約が多い。",
         "feature_en": "Adjacent to Shakujii Park — rare natural abundance within the 23 wards. Park-adjacent properties command premium closings.",
         "feature_zh": "毗邻石神井公园，在23区内属稀缺的丰富自然环境，公园临近物件易获溢价，高价成交案例多见。",
         "demand": "自然志向富裕ファミリー",
         "demand_en": "Nature-oriented affluent families",
         "demand_zh": "自然志向富裕家庭",
         "trend": "上昇"},
        {"name": "光が丘", "name_en": "Hikarigaoka",
         "mansion": "85〜145万円/㎡", "land": "135〜215万円/㎡",
         "feature": "大規模計画都市として整備された住環境の良いエリア。街全体がコンパクトシティとして機能し、住民満足度が高い。",
         "feature_en": "Well-developed planned residential city. The compact city design functions well; high resident satisfaction.",
         "feature_zh": "作为大规模计划城市整备的优质居住区，全域紧凑型城市功能完善，居民满意度高。",
         "demand": "ファミリー実需",
         "demand_en": "Family real demand",
         "demand_zh": "家庭实需",
         "trend": "安定"},
        {"name": "大泉学園", "name_en": "Ōizumigakuen",
         "mansion": "85〜145万円/㎡", "land": "135〜215万円/㎡",
         "feature": "アニメ・映像業界が集積するエリア。クリエイター需要と緑豊かな環境で独自の価値を持つ。",
         "feature_en": "Area with anime and film industry concentration. Unique value from creator demand and lush green environment.",
         "feature_zh": "动漫及影视业聚集区域，创意人士需求与绿意盎然环境共同构成独特价值。",
         "demand": "クリエイター・ファミリー",
         "demand_en": "Creatives, families",
         "demand_zh": "创意人士・家庭",
         "trend": "緩やかな上昇"},
        {"name": "東長崎", "name_en": "Higashi-Naganuki",
         "mansion": "100〜170万円/㎡", "land": "160〜250万円/㎡",
         "feature": "西武池袋線で池袋直通5分。練馬区内でも都心へのアクセスが良好で、ビジネス層の需要が安定。",
         "feature_en": "Direct Seibu Ikebukuro Line to Ikebukuro in 5 minutes. Good city access within Nerima; stable business worker demand.",
         "feature_zh": "西武池袋线直达池袋仅需5分钟，在练马区内都心可达性优良，商务层需求稳定。",
         "demand": "ビジネス層・ファミリー実需",
         "demand_en": "Business workers, family real demand",
         "demand_zh": "商务层・家庭实需",
         "trend": "安定上昇"},
        {"name": "江古田", "name_en": "Ekoda",
         "mansion": "100〜165万円/㎡", "land": "155〜245万円/㎡",
         "feature": "音楽大学・芸術大学が集積する文教エリア。学生・芸術家の街として独自のカルチャーがあり、独特の需要層を持つ。",
         "feature_en": "Academic area with music and arts universities. Unique culture and demand base as a student and artist neighborhood.",
         "feature_zh": "音乐大学及艺术大学集聚的文教区域，作为学生及艺术家街区具有独特文化，拥有特殊需求层。",
         "demand": "芸術系学生・クリエイター",
         "demand_en": "Arts students, creatives",
         "demand_zh": "艺术系学生・创意人士",
         "trend": "安定"},
    ],
    "adachi": [
        {"name": "北千住", "name_en": "Kita-Senju",
         "mansion": "95〜165万円/㎡", "land": "155〜245万円/㎡",
         "feature": "複数の大学が集積し若年層の流入が急増中。再開発とイメージ改善で価格が継続上昇しており、今が最大の売り時。",
         "feature_en": "Multiple universities concentrating here; young resident inflow surging. Prices continuously rising through redevelopment and image improvement.",
         "feature_zh": "多所大学集聚，年轻层流入急速增加，凭借再开发及形象改善价格持续上涨，现在是最佳出售时机。",
         "demand": "大学生・若年ビジネス層・投資家",
         "demand_en": "University students, young business workers, investors",
         "demand_zh": "大学生・年轻商务层・投资者",
         "trend": "強い上昇"},
        {"name": "西新井", "name_en": "Nishi-Arai",
         "mansion": "75〜130万円/㎡", "land": "120〜200万円/㎡",
         "feature": "東武スカイツリーラインで押上・浅草直通。価格が手頃で賃貸利回りが高く、投資家からの引き合いが多い。",
         "feature_en": "Direct Tobu Skytree Line access to Oshiage and Asakusa. Affordable with high rental yields; strong investor inquiries.",
         "feature_zh": "东武晴空塔线直达押上及浅草，价格合理、租赁收益高，投资者询盘旺盛。",
         "demand": "投資家・ファミリー実需",
         "demand_en": "Investors, family real demand",
         "demand_zh": "投资者・家庭实需",
         "trend": "緩やかな上昇"},
        {"name": "竹ノ塚", "name_en": "Takenotsuka",
         "mansion": "70〜120万円/㎡", "land": "115〜185万円/㎡",
         "feature": "東武スカイツリーライン沿線。足立区内でも価格が手頃で、高利回り投資物件として投資家需要が旺盛。",
         "feature_en": "Along Tobu Skytree Line. Very affordable even within Adachi; roaring high-yield investment demand.",
         "feature_zh": "东武晴空塔线沿线，在足立区内价格也属合理，高收益投资物件的投资者需求旺盛。",
         "demand": "高利回り投資家",
         "demand_en": "High-yield investors",
         "demand_zh": "高收益投资者",
         "trend": "緩やかな上昇"},
        {"name": "綾瀬", "name_en": "Ayase",
         "mansion": "75〜130万円/㎡", "land": "120〜195万円/㎡",
         "feature": "東京メトロ千代田線で大手町直通。都心直結路線沿線として実需・投資双方の需要が安定。",
         "feature_en": "Tokyo Metro Chiyoda Line with direct access to Otemachi. Stable dual real demand and investment demand along city-direct line.",
         "feature_zh": "东京地铁千代田线直达大手町，作为都心直连线路沿线，实需及投资双重需求稳定。",
         "demand": "ファミリー実需・投資家",
         "demand_en": "Family real demand, investors",
         "demand_zh": "家庭实需・投资者",
         "trend": "安定上昇"},
        {"name": "梅島", "name_en": "Umeshima",
         "mansion": "75〜130万円/㎡", "land": "120〜195万円/㎡",
         "feature": "東武スカイツリーラインで浅草・押上方面へのアクセスが良好。価格が手頃で実需ファミリー層の購入が多い。",
         "feature_en": "Good access toward Asakusa and Oshiage on Tobu Skytree Line. Affordable; many genuine family buyer purchases.",
         "feature_zh": "东武晴空塔线通往浅草及押上方向可达性优良，价格合理，实需家庭层购买者众多。",
         "demand": "ファミリー実需",
         "demand_en": "Family real demand",
         "demand_zh": "家庭实需",
         "trend": "安定"},
    ],
    "katsushika": [
        {"name": "金町", "name_en": "Kanamachi",
         "mansion": "80〜140万円/㎡", "land": "130〜210万円/㎡",
         "feature": "JR常磐線で上野直通。価格が手頃で広い物件が多く、都心から移住するファミリー層の需要が増加中。",
         "feature_en": "Direct JR Jōban Line to Ueno. Affordable with many spacious properties; increasing family migration from the city.",
         "feature_zh": "JR常磐线直达上野，价格合理、宽敞物件众多，从都心移居的家庭层需求持续增加。",
         "demand": "ファミリー実需・都心移住者",
         "demand_en": "Family real demand, urban migrants",
         "demand_zh": "家庭实需・都心移居者",
         "trend": "緩やかな上昇"},
        {"name": "亀有", "name_en": "Kameari",
         "mansion": "80〜140万円/㎡", "land": "130〜210万円/㎡",
         "feature": "「こち亀」で知名度抜群の親しみやすいエリア。実需購入者が多く、手頃な価格帯で早期成約が狙える。",
         "feature_en": "Instantly recognizable from the 'Kochikame' manga. Many genuine buyers; favorable for fast closing at affordable price range.",
         "feature_zh": "因《乌龙派出所》而广为人知的亲切区域，实需购买者众多，价格合理可实现早期成交。",
         "demand": "ファミリー実需",
         "demand_en": "Family real demand",
         "demand_zh": "家庭实需",
         "trend": "安定"},
        {"name": "新小岩", "name_en": "Shin-Koiwa",
         "mansion": "85〜145万円/㎡", "land": "135〜215万円/㎡",
         "feature": "JR総武線で秋葉原・東京直通。再開発が進んでおり、エリア全体の価値が底上げされている。",
         "feature_en": "Direct JR Sōbu Line to Akihabara and Tokyo Station. Redevelopment underway; overall area value is being lifted.",
         "feature_zh": "JR总武线直达秋叶原及东京站，再开发推进中，整体区域价值正在底部抬升。",
         "demand": "ファミリー実需・投資家",
         "demand_en": "Family real demand, investors",
         "demand_zh": "家庭实需・投资者",
         "trend": "上昇"},
        {"name": "柴又", "name_en": "Shibamata",
         "mansion": "70〜125万円/㎡", "land": "115〜195万円/㎡",
         "feature": "「男はつらいよ」の聖地として外国人観光客にも絶大な知名度。収益物件・民泊転用での高値売却が期待できる。",
         "feature_en": "Sacred ground of 'Tora-san' films with overwhelming name recognition among foreign tourists. Premium income property and minpaku conversion exit potential.",
         "feature_zh": "作为《男人真命苦》的圣地在外国游客中享有极高知名度，可期待收益物件及民宿转用的高价出售。",
         "demand": "インバウンド投資家・民泊事業者",
         "demand_en": "Inbound investors, minpaku operators",
         "demand_zh": "入境投资者・民宿运营者",
         "trend": "緩やかな上昇"},
        {"name": "青砥", "name_en": "Aoto",
         "mansion": "80〜140万円/㎡", "land": "130〜210万円/㎡",
         "feature": "京成線で押上・成田空港方面へのアクセスが良好。外国人居住者が多く、外語対応物件の需要が強い。",
         "feature_en": "Keisei Line access toward Oshiage and Narita Airport. Many foreign residents; strong demand for multilingual-friendly properties.",
         "feature_zh": "京成线通往押上及成田机场方向可达性优良，外国居民众多，外语对应物件需求强劲。",
         "demand": "外国人居住者・ファミリー実需",
         "demand_en": "Foreign residents, family real demand",
         "demand_zh": "外国居民・家庭实需",
         "trend": "安定"},
    ],
    "edogawa": [
        {"name": "葛西", "name_en": "Kasai",
         "mansion": "85〜150万円/㎡", "land": "135〜220万円/㎡",
         "feature": "葛西臨海公園隣接で自然環境が豊富。子育て支援が充実しており、ファミリー移住先として全国的に知名度がある。",
         "feature_en": "Adjacent to Kasai Rinkai Park; rich natural environment. Outstanding childcare support gives it national name recognition as a family relocation destination.",
         "feature_zh": "毗邻葛西临海公园自然环境丰富，育儿支援充实，作为家庭移居目的地享有全国知名度。",
         "demand": "ファミリー実需・子育て世代",
         "demand_en": "Family real demand, child-rearing generation",
         "demand_zh": "家庭实需・育儿世代",
         "trend": "安定上昇"},
        {"name": "小岩", "name_en": "Koiwa",
         "mansion": "90〜155万円/㎡", "land": "145〜225万円/㎡",
         "feature": "JR総武線で秋葉原・東京直通。外国人居住者比率が高く、外語対応物件の需要が旺盛。",
         "feature_en": "Direct JR Sōbu Line to Akihabara and Tokyo Station. High foreign resident ratio; strong demand for multilingual-friendly properties.",
         "feature_zh": "JR总武线直达秋叶原及东京站，外国居民比例高，外语对应物件需求旺盛。",
         "demand": "外国人居住者・ファミリー実需",
         "demand_en": "Foreign residents, family real demand",
         "demand_zh": "外国居民・家庭实需",
         "trend": "安定上昇"},
        {"name": "平井", "name_en": "Hirai",
         "mansion": "85〜145万円/㎡", "land": "135〜215万円/㎡",
         "feature": "総武線で秋葉原・錦糸町へのアクセスが良好。昔ながらの商店街と戸建て住宅が多く、地元実需が安定している。",
         "feature_en": "Good Sōbu Line access to Akihabara and Kinshichō. Traditional shopping street and detached homes; stable local real demand.",
         "feature_zh": "总武线通往秋叶原及锦丝町便利，传统商店街及独栋住宅众多，本地实需稳定。",
         "demand": "地元実需・ファミリー",
         "demand_en": "Local real demand, families",
         "demand_zh": "本地实需・家庭",
         "trend": "緩やかな上昇"},
        {"name": "一之江", "name_en": "Ichinoe",
         "mansion": "80〜140万円/㎡", "land": "130〜205万円/㎡",
         "feature": "都営新宿線沿線で新宿直通。江戸川区内でも利便性が高く、ファミリー実需が安定している。",
         "feature_en": "Toei Shinjuku Line with direct access to Shinjuku. High convenience within Edogawa; stable family real demand.",
         "feature_zh": "都营新宿线直达新宿，在江户川区内便利性高，家庭实需稳定。",
         "demand": "ファミリー実需",
         "demand_en": "Family real demand",
         "demand_zh": "家庭实需",
         "trend": "安定"},
        {"name": "瑞江", "name_en": "Mizue",
         "mansion": "80〜135万円/㎡", "land": "125〜200万円/㎡",
         "feature": "都営新宿線沿線の閑静な住宅地。江戸川区内で比較的落ち着いたエリアで、長期定住需要が安定。",
         "feature_en": "Quiet residential area along Toei Shinjuku Line. Calm area within Edogawa; stable long-term settlement demand.",
         "feature_zh": "都营新宿线沿线宁静住宅地，在江户川区内属较安静区域，长期定居需求稳定。",
         "demand": "ファミリー実需・長期定住層",
         "demand_en": "Family real demand, long-term residents",
         "demand_zh": "家庭实需・长期定居层",
         "trend": "安定"},
    ],
}
